services:
  user-service:
    build: ./services/user-service
    restart: always
    ports:
      - "4001:4000"
    depends_on:
      - rabbitmq
      - mongodb
  post-service:
    build: ./services/post-service
    restart: always
    ports:
      - "4002:4000"
    depends_on:
      - rabbitmq
      - postgres

  message-service:
    build: ./services/message-service
    restart: always
    ports:
      - "4003:4000"
    depends_on:
      - rabbitmq
      - redis

  notification-service:
    build: ./services/notification-service
    restart: always
    ports:
      - "4004:4000"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USR}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  postgres-data:
